"""Create Game Model

Revision ID: 11be35399c5e
Revises: dcac2f1afa99
Create Date: 2023-08-31 15:50:38.171967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11be35399c5e'
down_revision = 'dcac2f1afa99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
