"""cascade all and delete-orphan added 

Revision ID: 269dbd3435dc
Revises: d17ce46b8fe6
Create Date: 2023-08-31 17:19:23.471152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269dbd3435dc'
down_revision = 'd17ce46b8fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
